name: CI/CD for Wisecow Application on Minikube

on:
  push:
    branches:
      - main  # Update the branch name if necessary

env:
  KUBE_CLIENT_CERT: ${{ secrets.KUBE_CLIENT_CERT }}
  KUBE_CLIENT_KEY: ${{ secrets.KUBE_CLIENT_KEY }}
  KUBE_CA_CERT: ${{ secrets.KUBE_CA_CERT }}
  MINIKUBE_IP: 192.168.49.2  # The default IP for Minikube, update if different

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GIT_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/gmohbey/wisecow-app:latest -f docker/Dockerfile docker/

      - name: Push Docker image
        run: docker push ghcr.io/gmohbey/wisecow-app:latest

  deploy:
    name: Deploy to Minikube
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker
          minikube tunnel &

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube
        
      - name: Configure kubectl for Minikube
        run: |
          cat <<EOF > $HOME/.kube/config
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: "${{ env.KUBE_CA_CERT }}"
              server: https://192.168.49.2:8443  # Minikube's default IP
            name: minikube
          contexts:
          - context:
              cluster: minikube
              user: minikube-user
            name: minikube-context
          current-context: minikube-context
          kind: Config
          users:
          - name: minikube-user
            user:
              client-certificate-data: "${{ env.KUBE_CLIENT_CERT }}"
              client-key-data: "${{ env.KUBE_CLIENT_KEY }}"
          EOF

      - name: Apply Kubernetes Deployment and Service
        run: |
          kubectl apply --validate=false -f k8s/wisecow-unique-deployment.yaml
          kubectl apply --validate=false -f k8s/wisecow-unique-service.yaml

      - name: Update Deployment Image
        run: |
          kubectl set image deployment/wisecow-unique-deployment wisecow-container-unique=ghcr.io/gmohbey/wisecow-app:latest




