name: Minimal CI/CD Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  minimal-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GIT_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/gmohbey/wisecow-app:latest -f docker/Dockerfile .

      - name: Push Docker image
        run: |
          docker push ghcr.io/gmohbey/wisecow-app:latest

  validate-kubectl:
    needs: minimal-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CA_CERT }}" | base64 --decode > $HOME/.kube/minikube-ca.crt
          echo "apiVersion: v1" > $HOME/.kube/config
          echo "clusters:" >> $HOME/.kube/config
          echo "- cluster:" >> $HOME/.kube/config
          echo "    certificate-authority: $HOME/.kube/minikube-ca.crt" >> $HOME/.kube/config
          echo "    server: https://192.168.49.2:8443" >> $HOME/.kube/config
          echo "  name: minikube" >> $HOME/.kube/config
          echo "contexts:" >> $HOME/.kube/config
          echo "- context:" >> $HOME/.kube/config
          echo "    cluster: minikube" >> $HOME/.kube/config
          echo "    user: minikube-user" >> $HOME/.kube/config
          echo "  name: minikube-context" >> $HOME/.kube/config
          echo "current-context: minikube-context" >> $HOME/.kube/config
          echo "kind: Config" >> $HOME/.kube/config
          echo "users:" >> $HOME/.kube/config
          echo "- name: minikube-user" >> $HOME/.kube/config
          echo "  user:" >> $HOME/.kube/config
          echo "    client-certificate: ${{ secrets.KUBE_CLIENT_CERT }}" >> $HOME/.kube/config
          echo "    client-key: ${{ secrets.KUBE_CLIENT_KEY }}" >> $HOME/.kube/config

      - name: Validate kubectl configuration
        run: kubectl config view
