name: CI/CD for Wisecow Application

on:
  push:
    branches:
      - main  # Adjust as necessary
  workflow_dispatch:  # Enables manual triggering

env:
  KUBE_CLIENT_CERT: ${{ secrets.KUBE_CLIENT_CERT }}
  KUBE_CLIENT_KEY: ${{ secrets.KUBE_CLIENT_KEY }}
  KUBE_CA_CERT: ${{ secrets.KUBE_CA_CERT }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GIT_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/gmohbey/wisecow-app:latest -f docker/Dockerfile docker/

      - name: Push Docker image
        run: docker push ghcr.io/gmohbey/wisecow-app:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push  # Ensure this job runs after the build-and-push job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Decode and Add Minikube CA certificate
        run: echo "${{ secrets.KUBE_CA_CERT }}" | base64 --decode > $HOME/.kube/minikube-ca.crt

      - name: Configure kubectl
           run:|-
                  cat > $HOME/.kube/config <<EOF
  apiVersion: v1
  clusters:
    - cluster:
        certificate-authority: $HOME/.kube/minikube-ca.crt
        server: https://192.168.49.2:8443
      name: minikube
  contexts:
    - context:
        cluster: minikube
        user: minikube-user
      name: minikube-context
  current-context: minikube-context
  kind: Config
  users:
    - name: minikube-user
      user:
        client-certificate-data: "${{ env.KUBE_CLIENT_CERT }}"
        client-key-data: "${{ env.KUBE_CLIENT_KEY }}"
    EOF

      - name: Deploy to Kubernetes
        run: kubectl set image deployment/wisecow-unique-deployment wisecow-container-unique=ghcr.io/gmohbey/wisecow-app:latest
