name: CI/CD for Wisecow Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GIT_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/gmohbey/wisecow-app:latest -f docker/Dockerfile .

      - name: Push Docker image
        run: |
          docker push ghcr.io/gmohbey/wisecow-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Kind
      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      # Create Kind cluster
      - name: Create Kind cluster
        run: kind create cluster

      # Check cluster info
      - name: Check Kubernetes cluster info
        run: kubectl cluster-info --context kind-kind

      # Deploy to Kind cluster
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f - --validate=false <<EOF
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: wisecow-app
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: wisecow
            template:
              metadata:
                labels:
                  app: wisecow
              spec:
                containers:
                - name: wisecow-app
                  image: ghcr.io/gmohbey/wisecow-app:latest
                imagePullSecrets:
                - name: ghcr-secret
          EOF
